server:
  port: 8080

spring:
  application:
    name: ingestor-service
  kafka:
    bootstrap-servers: kafka:9092
    properties:
      schema.registry.url: http://schema-registry:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    com.dronelogistics.ingestorservice: DEBUG
